trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: './az-204/demo-02/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore $(solution)
  displayName: 'dotnet restore $(solution)'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(solution) --configuration $(buildConfiguration)'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'acrapidemoaz204'
    repository: './az204/demo-02'
    command: 'buildAndPush'
    Dockerfile: './az-204/demo-02/MyWebApiProject/Dockerfile'