trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: './az-204/demo-02/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore $(solution)
  displayName: 'dotnet restore $(solution)'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(solution) --configuration $(buildConfiguration)'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7' # Versão específica do Docker

# Autenticação com Username and Password
- task: Docker@2
  displayName: Build and Push Docker image
  inputs:
    containerRegistry: 'DockerRegistryConnection' # Nome da conexão de serviço do Docker Registry
    repository: 'mywebapiproject' # Nome do repositório no ACR
    command: 'buildAndPush'
    Dockerfile: './az-204/demo-02/MyWebApiProject/Dockerfile'
    tags: |
      $(Build.BuildId)
    containerRegistryType: 'Others'